name: action-git-auth
description: Injects git auth credentials into the host using .insteadOf rules in global .gitconfig
inputs:
  token:
    description: GitHub personal access token
    required: true
  prefix:
    description: URL path prefix to rewrite
    required: false
    default: ""
  server:
    description: GitHub server name, if not using hosted
    required: false
    default: ""
runs:
  using: "node12"
  # pre: 'dist/index.js'
  main: "dist/main/index.js"
  post: "dist/post/index.js"
