name: action-git-auth
description:
  This [GitHub Action](https://docs.github.com/en/actions) provides a way to
  configure credentials for any utility that uses the git command, or any
  utility that uses the git command as a subprocess, or any utility that uses
  the git configuration file in its authentication and cloning.
inputs:
  github-personal-access-token:
    description:
      A GitHub personal access token that has appropriate access in the consumer
      GitHub repository that will be used for authentication with GitHub.
    required: true
  prefix:
    description:
      The prefix to use for the URL path rewrite. This will often be an
      organization name if you wish to limit which repositories are accessible.
    required: false
    default: ""
  server:
    description:
      The name of the GitHub server to use, if not using hosted. This is useful
      if you are running this action against a GitHub Enterprise instance.
    required: false
    default: ""
runs:
  ## Injects git auth credentials into the host using .insteadOf rules in
  ## global .gitconfig.
  using: "node20"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
